from setuptools import setup

setup(
    name='sppas',
    version='2.2',
    packages=['sppas', 'sppas.bin', 'sppas.src', 'sppas.src.ui', 'sppas.src.ui.term', 'sppas.src.ui.wxgui',
              'sppas.src.ui.wxgui.ui', 'sppas.src.ui.wxgui.views', 'sppas.src.ui.wxgui.cutils',
              'sppas.src.ui.wxgui.frames', 'sppas.src.ui.wxgui.panels', 'sppas.src.ui.wxgui.clients',
              'sppas.src.ui.wxgui.dialogs', 'sppas.src.ui.wxgui.process', 'sppas.src.ui.wxgui.structs',
              'sppas.src.ui.phoenix', 'sppas.src.ui.phoenix.tests', 'sppas.src.ui.phoenix.dialogs',
              'sppas.src.ui.phoenix.windows', 'sppas.src.ui.phoenix.page_home', 'sppas.src.ui.phoenix.page_files',
              'sppas.src.ui.phoenix.page_analyze', 'sppas.src.ui.phoenix.page_plugins',
              'sppas.src.ui.phoenix.page_annotate', 'sppas.src.files', 'sppas.src.utils', 'sppas.src.utils.tests',
              'sppas.src.config', 'sppas.src.models', 'sppas.src.models.acm', 'sppas.src.models.slm',
              'sppas.src.models.tests', 'sppas.src.anndata', 'sppas.src.anndata.aio', 'sppas.src.anndata.ann',
              'sppas.src.anndata.ann.annlabel', 'sppas.src.anndata.ann.annlocation', 'sppas.src.anndata.tests',
              'sppas.src.plugins', 'sppas.src.plugins.tests', 'sppas.src.structs', 'sppas.src.structs.tests',
              'sppas.src.analysis', 'sppas.src.analysis.tests', 'sppas.src.calculus', 'sppas.src.calculus.stats',
              'sppas.src.calculus.tests', 'sppas.src.calculus.scoring', 'sppas.src.calculus.geometry',
              'sppas.src.calculus.infotheory', 'sppas.src.audiodata', 'sppas.src.audiodata.aio',
              'sppas.src.audiodata.tests', 'sppas.src.resources', 'sppas.src.resources.tests', 'sppas.src.presenters',
              'sppas.src.presenters.tests', 'sppas.src.annotations', 'sppas.src.annotations.TGA',
              'sppas.src.annotations.Phon', 'sppas.src.annotations.Syll', 'sppas.src.annotations.Align',
              'sppas.src.annotations.Align.aligners', 'sppas.src.annotations.Momel', 'sppas.src.annotations.tests',
              'sppas.src.annotations.Intsint', 'sppas.src.annotations.FillIPUs', 'sppas.src.annotations.TextNorm',
              'sppas.src.annotations.SelfRepet', 'sppas.src.annotations.OtherRepet', 'sppas.src.annotations.SearchIPUs',
              'sppas.src.dependencies', 'sppas.src.dependencies.grako', 'sppas.src.dependencies.grako.test',
              'sppas.src.dependencies.grako.codegen'],
    url='http://www.sppas.org/',
    license='GNU GPL v3',
    author='Brigitte Bigi',
    author_email='contacts@sppas.org',
    description='SPPAS - the automatic annotation and analysis of speech'
)
